using ParagonPioneers2ProductionCalculator.Buildings.HighSeas.Adepts;
using ParagonPioneers2ProductionCalculator.Buildings.HighSeas.Apprentices;
using ParagonPioneers2ProductionCalculator.Buildings.HighSeas.Archmages;
using ParagonPioneers2ProductionCalculator.Buildings.Northern;
using ParagonPioneers2ProductionCalculator.Buildings.Southern.Farmers;
using ParagonPioneers2ProductionCalculator.Buildings.Southern.Workers;
using ParagonPioneers2ProductionCalculator.Buildings.Temperate.Colonists;
using ParagonPioneers2ProductionCalculator.Buildings.Temperate.Merchants;
using ParagonPioneers2ProductionCalculator.Buildings.Temperate.Paragons;
using ParagonPioneers2ProductionCalculator.Buildings.Temperate.Pioneers;
using ParagonPioneers2ProductionCalculator.Buildings.Temperate.Townsmen;

namespace ParagonPioneers2ProductionCalculator.Buildings;

public static class SupplierConfiguration
{
	public static List<AbstractBuilding> GetSupplier(eGood good)
	{
		return good switch
		{
			eGood.Ambergris => [new AmbergrisProduction()],
			eGood.ArmoredHorse => [new Armorsmith()],
			eGood.Ball => [new BallMaker()],
			eGood.Barrel => [new Cooper()],
			eGood.Beer => [new Brewery()],
			eGood.Book => [new Bookbinder()],
			eGood.Bow => [new Bowyer()],
			eGood.Brandy => [new BrandyDistillery()],
			eGood.BrassIngot => [new Temperate.Paragons.BrassSmelter(), new Southern.Workers.BrassSmelter(), new Northern.BrassSmelter()],
			eGood.Bread => [new Bakery()],
			eGood.Brick => [new Brickyard()],
			eGood.BrocadeFabric => [new BrocadeSpinningFactory()],
			eGood.Cacao => [new CacaoPlantation()],
			eGood.Candle => [new Chandler()],
			eGood.CandleHolder => [new FineForge()],
			eGood.Cannon => [new CannonFoundry()],
			eGood.Cattle => [new CattleRanch()],
			eGood.Cauldron => [new BoilerMaker()],
			eGood.Caviar => [new CaviarFactory()],
			eGood.Chalk => [new ChalkMaker()],
			eGood.Cheese => [new Dairy()],
			eGood.Chocolate => [new Chocolaterie()],
			eGood.ChocolateCandy => [new Confectionery()],
			eGood.Cider => [new CiderMaker()],
			eGood.Cigar => [new CigarManufacturer()],
			eGood.Clay => [new ClayPit()],
			eGood.Coal => [new Temperate.Townsmen.CoalMine(), new CharcoalKiln(), new Southern.Farmers.CoalMine(), new Northern.CoalMine()],
			eGood.Coconut => [new CoconutPlantation()],
			eGood.Coffee => [new RoastHouse()],
			eGood.CoffeeBeans => [new CoffeePlantation()],
			eGood.Coke => [new Cokery()],
			eGood.CompositeBow => [new CompositeBowyer()],
			eGood.CopperAxe => [new CopperAxesmith()],
			eGood.CopperIngot => [new Temperate.Colonists.CopperSmelter(), new Southern.Farmers.CopperSmelter(), new Northern.CopperSmelter()],
			eGood.CopperOre => [new Temperate.Colonists.CopperMine(), new DeepCopperMine(), new Southern.Farmers.CopperMine(), new Northern.CopperMine()],
			eGood.CopperSword => [new CopperArmory()],
			eGood.Costume => [new Costumier()],
			eGood.Crossbow => [new CrossbowMaker()],
			eGood.Dye => [new IndigoPlantation()],
			eGood.Egg => [new ChickenFarm()],
			eGood.Fabric => [new Weaver(), new TextileFactory(), new SpinningMill()],
			eGood.Feast => [new NobleKitchen()],
			eGood.Felt => [new FeltmakingMill()],
			eGood.Fiber => [new Temperate.Colonists.LinseedFarm(), new FiberMaker(), new HighSeas.Apprentices.LinseedFarm()],
			eGood.FineWood => [new FineWoodLogger()],
			eGood.Fireworks => [new FireworksMaker()],
			eGood.Fish => [new Temperate.Pioneers.FishermansHut(), new BeachFishermansHut(), new SalmonFishermansHut(), new HighSeas.Apprentices.FishermansHut()],
			eGood.FishOil => [new BoilingHouse()],
			eGood.Flour => [new FlourMill(), new FlourWindmill()],
			eGood.FuneralFlowers => [new FlowerHouse()],
			eGood.Garment => [new NobleTailor()],
			eGood.Gemstone => [new GemstoneMine()],
			eGood.Glaive => [new GlaiveSmith()],
			eGood.Glass => [new Glassworks()],
			eGood.Glasses => [new LensGrinder()],
			eGood.GoldIngot => [new Temperate.Merchants.GoldSmelter(), new Southern.Workers.GoldSmelter(), new GoldPanner(), new Northern.GoldSmelter()],
			eGood.GoldJewelry => [new Goldsmith(), new TreasureSeeker()],
			eGood.GoldOre => [new Southern.Workers.GoldMine(), new Northern.GoldMine()],
			eGood.Grapes => [new Winery()],
			eGood.Guitar => [new Luthier()],
			eGood.Gunpowder => [new PowderMill()],
			eGood.Hat => [new HattersShop()],
			eGood.Herbs => [new HerbalistsHut()],
			eGood.Hide => [new Furriery()],
			eGood.Honeycomb => [new Apiary()],
			eGood.Hops => [new HopFarm()],
			eGood.Horse => [new HorseBreeder()],
			eGood.IronIngot => [new Temperate.Merchants.IronSmelter(), new Northern.IronSmelter()],
			eGood.IronOre => [new Temperate.Merchants.IronMine(), new Northern.IronMine()],
			eGood.IronSword => [new IronArmory()],
			eGood.Jam => [new JamMaker()],
			eGood.LeadIngot => [new LeadSmelter()],
			eGood.LeadOre => [new LeadMine()],
			eGood.Leather => [new Tannery(), new CrocodileRanch()],
			eGood.Limestone => [new Stonecutter(), new BoulderGatherer()],
			eGood.Linen => [new LinenWeaver()],
			eGood.Liqueur => [new HoneyDistillery()],
			eGood.Lobster => [new Lobsterer()],
			eGood.Longbow => [new Longbowyer()],
			eGood.LongShield => [new HeraldicArmourer()],
			eGood.Malt => [new Malthouse()],
			eGood.Marble => [new Temperate.Merchants.MarbleQuarry(), new Northern.MarbleQuarry()],
			eGood.Meat => [new Butchery(), new BuffaloButchery()],
			eGood.MeatPie => [new PieMaker()],
			eGood.MedicinePouch => [new Apothecary()],
			eGood.MetalCuttings => [new PlaningMill()],
			eGood.Militia => [new PioneersHut()],
			eGood.Milk => [new GoatFarm()],
			eGood.Mojo => [new ArtisticBlacksmith()],
			eGood.Mortar => [new MortarBatchWorks()],
			eGood.Musket => [new MusketMaker()],
			eGood.NobleGarment => [new OrnateTailor()],
			eGood.Paper => [new PaperMill()],
			eGood.Pegasus => [new PegasusFarm()],
			eGood.Pelt => [new FurTrapper()],
			eGood.Perfume => [new Perfumery()],
			eGood.Pig => [new Piggery(), new PigRanch()],
			eGood.Pike => [new PoleturnersWorkshop()],
			eGood.PipeTobacco => [new CuringHouse()],
			eGood.Plank => [new SawWorks(), new Temperate.Pioneers.Sawmill(), new HighSeas.Apprentices.Sawmill()],
			eGood.Potash => [new AshHouse()],
			eGood.QuartzSand => [new QuartzQuarry()],
			eGood.Quicklime => [new LimeKiln()],
			eGood.RockSalt => [new Temperate.Townsmen.RockSaltMine(), new Northern.RockSaltMine()],
			eGood.Ropes => [new Temperate.Colonists.Ropery(), new Southern.Farmers.Ropery()],
			eGood.Rose => [new RoseCultivation()],
			eGood.RoseWater => [new EssenceDistillery()],
			eGood.RoughCloak => [new CloakTailoring()],
			eGood.Rum => [new RumDistillery()],
			eGood.Sail => [new Sailmaker()],
			eGood.Salt => [new Temperate.Townsmen.SaltWorks(), new Temperate.Paragons.Saltern(), new Southern.Farmers.Saltern(), new Northern.SaltWorks()],
			eGood.Sausage => [new SausageMaker()],
			eGood.Schnapps => [new PotatoFarm()],
			eGood.Shoe => [new CobblersShop()],
			eGood.Silk => [new SilkPlantation()],
			eGood.SilkFabric => [new SilkTwineMill()],
			eGood.Slinger => [new FarmersShack()],
			eGood.Soap => [new SoapMaker()],
			eGood.SpermWhale => [new Whaler()],
			eGood.SteelIngot => [new SteelFurnace()],
			eGood.Stew => [new SoupKitchen()],
			eGood.Strawberries => [new StrawberryFarm()],
			eGood.Sturgeon => [new SturgeonFarm()],
			eGood.Sugar => [new SugarBeetFarm(), new SugarMill(), new SugarWindmill()],
			eGood.SugarCane => [new SugarCanePlantation()],
			eGood.Tallow => [new RenderingWorks()],
			eGood.Tea => [new TeaPlantation()],
			eGood.Tobacco => [new TobaccoPlantation()],
			eGood.TobaccoPipe => [new PipemakersShop()],
			eGood.Tools => [new Toolmaker()],
			eGood.TournamentLance => [new LanceMaker()],
			eGood.Trophy => [new TrophyManufacturer()],
			eGood.Wand => [new WandmakersShop()],
			eGood.WarDrum => [new DrumMaker()],
			eGood.WaterBuffalo => [new WaterBuffaloRanch()],
			eGood.Wheat => [new WheatFarm()],
			eGood.Window => [new GlaziersWorkshop()],
			eGood.Wine => [new Winepress()],
			eGood.Wood => [new Temperate.Pioneers.Lumberjack(), new ForestWardensCabin(), new ConiferLumberjack(), new HighSeas.Apprentices.Lumberjack()],
			eGood.Yarn => [new SheepFarm(), new CottonPlantation()],
			eGood.ZincIngot => [new ZincSmelter()],
			eGood.ZincOre => [new ZincMine()],
			eGood.Saltpetre => [new NitrateMaker()],
			eGood.Basalt => [new Basaltcutter()],
			_ => []
		};
	}
}